theme: jekyll-theme-minimal

author:
  name   : "Ariel BLum"
  # avatar : "/assets/images/bio-photo.jpg"
  bio    : "Clinical Data scientist"
  links:
    - label: "LinkedIn"
      icon: "fas fa-fw fa-link"
      url: "https://www.linkedin.com/in/ariel-blum-416157248"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ab3263266"
